### ISSUE TITLE
Response undefined

### ISSUE THREAD

**Issue by etherealite** [justinjones/node-lol-client#14]
When running the example.js I have the same issue as mentioned in the icolor fork: https://github.com/iColor/league-node/issues/2

`````` sh
~/node-lol-client$ node example.js
Logging in..

/home/etherealite/node-lol-client/lol-client.js:114
            for (var i=0; i<response.tickers.length; i++){
                                            ^
TypeError: Cannot read property 'length' of undefined
    at /home/etherealite/node-lol-client/lol-client.js:114:45
    at IncomingMessage.<anonymous> (/home/etherealite/node-lol-client/lib/login-queue.js:19:16)
    at IncomingMessage.EventEmitter.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (_stream_readable.js:746:14)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at IncomingMessage.Readable.push (_stream_readable.js:127:10)
    at HTTPParser.parserOnBody [as onBody] (http.js:142:22)
```'

Node version v0.10.25
``````

**Comment by johnttan** [comment]
Have you tried updating the client version string to the latest client version?
In the options JSON.
